<?php
$l = 'hello welcome to , beijing  ';
$n = '123456';
$rand = rand(1000,9999);
echo count($l),'<br>';
echo strlen($l),'<br>';
echo strtolower($l),'<br>';
echo strtoupper($l),'<br>';
echo ucwords($l),'<br>';
echo ucfirst($l),'<br>';
echo strrev($l),'<br>';
echo strlen($l),'<br>';
echo strlen(trim($l)),'<br>';
echo str_replace('to','t*',$l),'<br>';
echo strpos($l,'to'),'<br>';
echo substr($l,-6,2),'<br>';
echo md5($n.$rand),'<br>';
echo md5($n.$rand),'<br>';
echo ("$n"."$rand"),'<br>';
unset($n);
for($i=0;$i<=5;$i+=1){	echo $i,' ';}echo '<br>';
echo "<table border=1>";for($j=1;$j<5;$j+=1){	echo "<tr>";for($i=1;$i<20;$i++){	echo "<td>  $i  </td>";}echo "</tr>";}echo "</table>";
